// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// OnetailedGSEA
RcppExport SEXP OnetailedGSEA(SEXP tvalue, SEXP genesetfile, SEXP min, SEXP max, SEXP nPerm, SEXP cutoff, SEXP q);
RcppExport SEXP AbsFilterGSEA_OnetailedGSEA(SEXP tvalueSEXP, SEXP genesetfileSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP nPermSEXP, SEXP cutoffSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type tvalue(tvalueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type genesetfile(genesetfileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min(minSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max(maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< SEXP >::type q(qSEXP);
    __result = Rcpp::wrap(OnetailedGSEA(tvalue, genesetfile, min, max, nPerm, cutoff, q));
    return __result;
END_RCPP
}
// TwotailedGSEA
RcppExport SEXP TwotailedGSEA(SEXP tvalue, SEXP genesetfile, SEXP min, SEXP max, SEXP nPerm, SEXP cutoff, SEXP q);
RcppExport SEXP AbsFilterGSEA_TwotailedGSEA(SEXP tvalueSEXP, SEXP genesetfileSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP nPermSEXP, SEXP cutoffSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type tvalue(tvalueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type genesetfile(genesetfileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min(minSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max(maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< SEXP >::type q(qSEXP);
    __result = Rcpp::wrap(TwotailedGSEA(tvalue, genesetfile, min, max, nPerm, cutoff, q));
    return __result;
END_RCPP
}
